"""
This module formats accident vehicles data.
"""

from pyspark import pipelines as dp
from pyspark.sql import functions as F

catalog = spark.conf.get("param_catalog")
schema_raw = spark.conf.get("param_schema_raw")

@dp.table(
    name="accident_vehicles_formated"
)
@dp.expect_or_drop("valid_accident_num", "accident_num IS NOT NULL")
def accident_vehicles_formated():
    """Format accident vehicles from raw data."""
    return (
        spark.read
        .table(f"{catalog}.{schema_raw}.accident_vehicles_raw")
        .withColumn("vehicle_direction", F.trim(F.col("vehicle_direction")))
        .withColumn(
            "vehicle_direction",
            F.when(F.col("vehicle_direction") == "-1", "Non renseigné")
             .when(F.col("vehicle_direction") == "0", "Inconnu")
             .when(F.col("vehicle_direction") == "1", "PK ou PR ou numéro d’adresse postale croissant")
             .when(F.col("vehicle_direction") == "2", "PK ou PR ou numéro d’adresse postale décroissant")
             .when(F.col("vehicle_direction") == "3", "Absence de repère")
             .otherwise("")
        )
        .withColumn("vehicle_category", F.trim(F.col("vehicle_category")))
        .withColumn(
            "vehicle_category",
            F.when(F.col("vehicle_category") == "0", "Indéterminable")
             .when(F.col("vehicle_category") == "1", "Bicyclette")
             .when(F.col("vehicle_category") == "2", "Cyclomoteur <50cm3")
             .when(F.col("vehicle_category") == "3", "Voiturette (Quadricycle à moteur carrossé)")
             .when(F.col("vehicle_category") == "4", "Référence inutilisée depuis 2006 (scooter immatriculé)")
             .when(F.col("vehicle_category") == "5", "Référence inutilisée depuis 2006 (motocyclette)")
             .when(F.col("vehicle_category") == "6", "Référence inutilisée depuis 2006 (side-car)")
             .when(F.col("vehicle_category") == "7", "VL seul")
             .when(F.col("vehicle_category") == "8", "Référence inutilisée depuis 2006 (VL + caravane)")
             .when(F.col("vehicle_category") == "9", "Référence inutilisée depuis 2006 (VL + remorque)")
             .when(F.col("vehicle_category") == "10", "VU seul 1,5T <= PTAC <= 3,5T avec ou sans remorque (anciennement VU seul 1,5T <= PTAC <= 3,5T)")
             .when(F.col("vehicle_category") == "11", "Référence inutilisée depuis 2006 (VU (10) + caravane)")
             .when(F.col("vehicle_category") == "12", "Référence inutilisée depuis 2006 (VU (10) + remorque)")
             .when(F.col("vehicle_category") == "13", "PL seul 3,5T <PTCA <= 7,5T")
             .when(F.col("vehicle_category") == "14", "PL seul > 7,5T")
             .when(F.col("vehicle_category") == "15", "PL > 3,5T + remorque")
             .when(F.col("vehicle_category") == "16", "Tracteur routier seul")
             .when(F.col("vehicle_category") == "17", "Tracteur routier + semi-remorque")
             .when(F.col("vehicle_category") == "18", "Référence inutilisée depuis 2006 (transport en commun)")
             .when(F.col("vehicle_category") == "19", "Référence inutilisée depuis 2006 (tramway)")
             .when(F.col("vehicle_category") == "20", "Engin spécial")
             .when(F.col("vehicle_category") == "21", "Tracteur agricole")
             .when(F.col("vehicle_category") == "30", "Scooter <50 cm3")
             .when(F.col("vehicle_category") == "31", "Motocyclette >50 cm3 et <=125 cm3")
             .when(F.col("vehicle_category") == "32", "Scooter >50 cm3 et <=125 cm3")
             .when(F.col("vehicle_category") == "33", "Motocyclette >125 cm3")
             .when(F.col("vehicle_category") == "34", "Scooter >125 cm3")
             .when(F.col("vehicle_category") == "35", "Quad léger <=50 cm3 (Quadricycle à moteur non carrossé)")
             .when(F.col("vehicle_category") == "36", "Quad lourd >50 cm3 (Quadricycle à moteur non carrossé)")
             .when(F.col("vehicle_category") == "37", "Autobus")
             .when(F.col("vehicle_category") == "38", "Autocar")
             .when(F.col("vehicle_category") == "39", "Train")
             .when(F.col("vehicle_category") == "40", "Tramway")
             .when(F.col("vehicle_category") == "41", "3RM <= 50 cm3")
             .when(F.col("vehicle_category") == "42", "3RM > 50 cm3 <= 125 cm3")
             .when(F.col("vehicle_category") == "43", "3RM > 125 cm3")
             .when(F.col("vehicle_category") == "50", "EDP à moteur")
             .when(F.col("vehicle_category") == "60", "EDP sans moteur")
             .when(F.col("vehicle_category") == "80", "VAE")
             .when(F.col("vehicle_category") == "99", "Autre véhicule")
            .otherwise("")
        )
        .withColumn("fixed_obstacle_struck", F.trim(F.col("fixed_obstacle_struck")))
        .withColumn(
            "fixed_obstacle_struck",
            F.when(F.col("fixed_obstacle_struck") == "-1", "Non renseigné")
             .when(F.col("fixed_obstacle_struck") == "0", "Sans objet")
             .when(F.col("fixed_obstacle_struck") == "1", "Véhicule en stationnement")
             .when(F.col("fixed_obstacle_struck") == "2", "Arbre")
             .when(F.col("fixed_obstacle_struck") == "3", "Glissière métallique")
             .when(F.col("fixed_obstacle_struck") == "4", "Glissière béton")
             .when(F.col("fixed_obstacle_struck") == "5", "Autre glissière")
             .when(F.col("fixed_obstacle_struck") == "6", "Bâtiment, mur, pile de pont")
             .when(F.col("fixed_obstacle_struck") == "7", "Support de signalisation verticale ou poste d’appel d’urgence")
             .when(F.col("fixed_obstacle_struck") == "8", "Poteau")
             .when(F.col("fixed_obstacle_struck") == "9", "Mobilier urbain")
             .when(F.col("fixed_obstacle_struck") == "10", "Parapet")
             .when(F.col("fixed_obstacle_struck") == "11", "Ilot, refuge, borne haute")
             .when(F.col("fixed_obstacle_struck") == "12", "Bordure de trottoir")
             .when(F.col("fixed_obstacle_struck") == "13", "Fossé, talus, paroi rocheuse")
             .when(F.col("fixed_obstacle_struck") == "14", "Autre obstacle fixe sur chaussée")
             .when(F.col("fixed_obstacle_struck") == "15", "Autre obstacle fixe sur trottoir ou accotement")
             .when(F.col("fixed_obstacle_struck") == "16", "Sortie de chaussée sans obstacle")
             .when(F.col("fixed_obstacle_struck") == "17", "Buse – tête d’aqueduc")
             .otherwise("")
        )
        .withColumn("moving_obstacle_struck", F.trim(F.col("moving_obstacle_struck")))
        .withColumn(
            "moving_obstacle_struck",
            F.when(F.col("moving_obstacle_struck") == "-1", "Non renseigné")
             .when(F.col("moving_obstacle_struck") == "0", "Aucun")
             .when(F.col("moving_obstacle_struck") == "1", "Piéton")
             .when(F.col("moving_obstacle_struck") == "2", "Véhicule")
             .when(F.col("moving_obstacle_struck") == "4", "Véhicule sur rail")
             .when(F.col("moving_obstacle_struck") == "5", "Animal domestique")
             .when(F.col("moving_obstacle_struck") == "6", "Animal sauvage")
             .when(F.col("moving_obstacle_struck") == "9", "Autre")
             .otherwise("")
        )
        .withColumn("initial_point_of_impact", F.trim(F.col("initial_point_of_impact")))
        .withColumn(
            "initial_point_of_impact",
            F.when(F.col("initial_point_of_impact") == "-1", "Non renseigné")
             .when(F.col("initial_point_of_impact") == "0", "Aucun")
             .when(F.col("initial_point_of_impact") == "1", "Avant")
             .when(F.col("initial_point_of_impact") == "2", "Avant droit")
             .when(F.col("initial_point_of_impact") == "3", "Avant gauche")
             .when(F.col("initial_point_of_impact") == "4", "Arrière")
             .when(F.col("initial_point_of_impact") == "5", "Arrière droit")
             .when(F.col("initial_point_of_impact") == "6", "Arrière gauche")
             .when(F.col("initial_point_of_impact") == "7", "Côté droit")
             .when(F.col("initial_point_of_impact") == "8", "Côté gauche")
             .when(F.col("initial_point_of_impact") == "9", "Chocs multiples (tonneaux)")
             .otherwise("")
        )
        .withColumn("main_maneuver_prior_accident", F.trim(F.col("main_maneuver_prior_accident")))
        .withColumn(
            "main_maneuver_prior_accident_group",
            F.when(F.col("main_maneuver_prior_accident").isin(["-1", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]), "Manoeuvre principale avant l’accident")
             .when(F.col("main_maneuver_prior_accident").isin(["11", "12"]), "Changeant de file")
             .when(F.col("main_maneuver_prior_accident").isin(["13", "14"]), "Déporté")
             .when(F.col("main_maneuver_prior_accident").isin(["15", "16"]), "Tournant")
             .when(F.col("main_maneuver_prior_accident").isin(["17", "18"]), "Dépassant")
             .when(F.col("main_maneuver_prior_accident").isin(["19", "20", "21", "22", "23", "24", "25", "26"]), "Divers")
             .otherwise("")
        )
        .withColumn(
            "main_maneuver_prior_accident_type",
            F.when(F.col("main_maneuver_prior_accident") == "-1", "Non renseigné")
             .when(F.col("main_maneuver_prior_accident") == "0", "Inconnue")
             .when(F.col("main_maneuver_prior_accident") == "1", "Sans changement de direction")
             .when(F.col("main_maneuver_prior_accident") == "2", "Même sens, même file")
             .when(F.col("main_maneuver_prior_accident") == "3", "Entre 2 files")
             .when(F.col("main_maneuver_prior_accident") == "4", "En marche arrière")
             .when(F.col("main_maneuver_prior_accident") == "5", "A contresens")
             .when(F.col("main_maneuver_prior_accident") == "6", "En franchissant le terre-plein central")
             .when(F.col("main_maneuver_prior_accident") == "7", "Dans le couloir bus, dans le même sens")
             .when(F.col("main_maneuver_prior_accident") == "8", "Dans le couloir bus, dans le sens inverse")
             .when(F.col("main_maneuver_prior_accident") == "9", "En s’insérant")
             .when(F.col("main_maneuver_prior_accident") == "10", "En faisant demi-tour sur la chaussée")
             .when(F.col("main_maneuver_prior_accident") == "11", "A gauche")
             .when(F.col("main_maneuver_prior_accident") == "12", "A droite")
             .when(F.col("main_maneuver_prior_accident") == "13", "A gauche")
             .when(F.col("main_maneuver_prior_accident") == "14", "A droite")
             .when(F.col("main_maneuver_prior_accident") == "15", "A gauche")
             .when(F.col("main_maneuver_prior_accident") == "16", "A droite")
             .when(F.col("main_maneuver_prior_accident") == "17", "A gauche")
             .when(F.col("main_maneuver_prior_accident") == "18", "A droite")
             .when(F.col("main_maneuver_prior_accident") == "19", "Traversant la chaussée")
             .when(F.col("main_maneuver_prior_accident") == "20", "Manœuvre de stationnement")
             .when(F.col("main_maneuver_prior_accident") == "21", "Manœuvre d’évitement")
             .when(F.col("main_maneuver_prior_accident") == "22", "Ouverture de porte")
             .when(F.col("main_maneuver_prior_accident") == "23", "Arrêté (hors stationnement)")
             .when(F.col("main_maneuver_prior_accident") == "24", "En stationnement (avec occupants)")
             .when(F.col("main_maneuver_prior_accident") == "25", "Circulant sur trottoir")
             .when(F.col("main_maneuver_prior_accident") == "26", "Autres manœuvres")
             .otherwise("")
        )
        .drop("main_maneuver_prior_accident")
        .withColumn(
            "vehicle_engine_type",
            F.when(F.col("vehicle_engine_type") == "-1", "Non renseigné")
             .when(F.col("vehicle_engine_type") == "0", "Inconnue")
             .when(F.col("vehicle_engine_type") == "1", "Hydrocarbures")
             .when(F.col("vehicle_engine_type") == "2", "Hybride électrique")
             .when(F.col("vehicle_engine_type") == "3", "Electrique")
             .when(F.col("vehicle_engine_type") == "4", "Hydrogène")
             .when(F.col("vehicle_engine_type") == "5", "Humaine")
             .when(F.col("vehicle_engine_type") == "6", "Autre")
             .otherwise("")
        )
    )


